spring:
  application:
    name: wiki-pulse-project

  profiles:
    default: yt

  jackson:
    property-naming-strategy: SNAKE_CASE

  mvc:
    problemdetails:
      enabled: true
  task:
    scheduling:
      pool:
        size: 2

app:
  ymaps:
    api-key: "${YMAPS_API_KEY:}"

  live:
    window-minutes: 30
    window-enabled: true
    #zoom <= zoom-r3-max  -> r3
    #zoom-r3-max < zoom <= zoom-r4-max -> r4, и так далее по ступеням
    #zoom > zoom-r8-max   -> r9
    zoom-min: 0          #карты начинаются с 0 весь мир
    zoom-max: 30         #потолок
    zoom-r3-max: 6       #маппинг zoom -> resolution
    zoom-r4-max: 7
    zoom-r5-max: 9
    zoom-r6-max: 11
    zoom-r8-max: 13
    hexagon-events-cap: 50        #максимум событий в массиве events в одном гексагоне(больше хранить очень тяжело да и не нужно - правок может быть тысячи)
  poller:
    interval-ms: 500
    start-from-beginning: false
    max-pages-per-tick: 10

yt:
  proxy: "${YT_PROXY}"
  token: "${YT_TOKEN}"
  timeout:
    ms: 30000

  table:
    q_enriched: //home/wikipulse/q_enriched
    marts:
      trends: //home/wikipulse/marts/trends
      top_articles: //home/wikipulse/marts/top_articles
      top_geo: //home/wikipulse/marts/top_geo
