spring:
  application:
    name: wiki-pulse-project
  profiles:
    default: mock
  jackson:
    property-naming-strategy: SNAKE_CASE
  mvc:
    problemdetails:
      enabled: true

app:
  live-window-seconds: 60
  yt:
    proxy-url: ${YT_PROXY:http://localhost:8000}
    token: ${YT_TOKEN:}
    queue-path: ${YT_QUEUE_PATH://home/wikpulse/Q_ENRICHED}
    consumer: ${YT_CONSUMER:c_rt}
    aggregates-path: ${YT_AGGREGATES_PATH://home/wikpulse/aggregates}
